"""Accept/reject policy. Deliberately kept out of the LLM so it stays auditable."""

from __future__ import annotations

import re
from dataclasses import dataclass

from .config import LABEL_TO_FOLDER, Settings
from .extract import ExtractedDoc
from .schema import Verdict

UNDETERMINED = "Undetermined"


@dataclass
class Decision:
    status: str          # "accepted" | "rejected"
    reason: str          # "none" or one of config.REJECT_REASONS
    explanation: str     # human-readable, shown in the UI and the report
    role_label: str      # e.g. "Data Scientist"
    role_folder: str     # e.g. "Data_Scientists"

    @property
    def accepted(self) -> bool:
        return self.status == "accepted"


def slugify(value: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_")
    return slug or UNDETERMINED


def role_folder_for(verdict: Verdict, settings: Settings) -> tuple[str, str]:
    """Resolve (display label, folder name) for a verdict."""
    label = verdict.role_family

    if label == "Other" and verdict.custom_role_title.strip():
        title = verdict.custom_role_title.strip()
        slug = slugify(title)
        return title, slug if slug.endswith("s") else f"{slug}s"

    if label == UNDETERMINED:
        return UNDETERMINED, LABEL_TO_FOLDER[UNDETERMINED]

    # A low-confidence guess is worse than admitting we do not know: it buries the
    # CV in the wrong folder where nobody will look for it.
    if verdict.role_confidence < settings.min_role_confidence:
        return UNDETERMINED, LABEL_TO_FOLDER[UNDETERMINED]

    return label, LABEL_TO_FOLDER.get(label, LABEL_TO_FOLDER["Other"])


def decide(verdict: Verdict, doc: ExtractedDoc, settings: Settings) -> Decision:
    """Apply the rejection rules in priority order."""
    label, folder = role_folder_for(verdict, settings)

    # 1. Not a CV at all - no role, so it cannot be filed under one.
    if not verdict.is_cv or verdict.document_type != "cv_resume":
        return Decision(
            status="rejected",
            reason="not_a_cv",
            explanation=(
                f"Not a CV - detected as '{verdict.document_type.replace('_', ' ')}'. "
                f"{verdict.reasoning}"
            ),
            role_label=label,
            role_folder=folder,
        )

    # 2. Generated by an LLM.
    if verdict.ai_generated_score >= settings.ai_threshold:
        signals = "; ".join(verdict.ai_signals[:3]) or verdict.reasoning
        return Decision(
            status="rejected",
            reason="ai_generated",
            explanation=(
                f"Likely AI-generated ({verdict.ai_generated_score}/100, threshold "
                f"{settings.ai_threshold}). {signals}"
            ),
            role_label=label,
            role_folder=folder,
        )

    # 3. A real CV, but with nothing in it to evaluate.
    if doc.char_count < settings.min_chars and not doc.needs_vision:
        return Decision(
            status="rejected",
            reason="insufficient_content",
            explanation=(
                f"Only {doc.char_count} characters of usable content - too thin to screen."
            ),
            role_label=label,
            role_folder=folder,
        )

    return Decision(
        status="accepted",
        reason="none",
        explanation=verdict.reasoning,
        role_label=label,
        role_folder=folder,
    )


def rejection_for_broken_file(doc: ExtractedDoc, message: str) -> Decision:
    """Decision for a file that never reached the LLM."""
    return Decision(
        status="rejected",
        reason="unreadable",
        explanation=message or doc.error or "The file could not be read.",
        role_label=UNDETERMINED,
        role_folder=LABEL_TO_FOLDER[UNDETERMINED],
    )
