"""Text + forensic-metadata extraction from CV files."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from .config import SUPPORTED_EXTENSIONS

# Producers/creators that indicate the file was printed straight out of a browser
# or generated by a script rather than saved from a normal word processor.
_SUSPICIOUS_PRODUCERS = (
    "skia/pdf",        # Chrome / Chromium "print to PDF" - common for LLM web output
    "python-docx",
    "reportlab",
    "wkhtmltopdf",
    "weasyprint",
    "puppeteer",
    "headlesschrome",
)


@dataclass
class ExtractedDoc:
    """Everything we know about a file before it reaches the LLM."""

    path: Path
    text: str = ""
    meta: dict[str, str] = field(default_factory=dict)
    page_count: int = 0
    needs_vision: bool = False   # PDF with no extractable text -> send the file itself
    error: str = ""

    @property
    def char_count(self) -> int:
        return len(self.text.strip())

    @property
    def metadata_flags(self) -> list[str]:
        """Forensic hints handed to the LLM as supporting (not deciding) evidence."""
        flags: list[str] = []
        blob = " ".join(f"{k}={v}" for k, v in self.meta.items()).lower()
        for producer in _SUSPICIOUS_PRODUCERS:
            if producer in blob:
                flags.append(f"File was produced by '{producer}' rather than a normal word processor")
        created, modified = self.meta.get("created", ""), self.meta.get("modified", "")
        if created and created == modified:
            flags.append("Creation and last-modified timestamps are identical (no editing history)")
        if self.meta.get("revision") in {"1", "0"}:
            flags.append("Document revision number is 1 (saved once, never revised)")
        return flags


def _clean(text: str) -> str:
    text = text.replace("\u0000", " ").replace("\uf0b7", "- ")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _extract_pdf(path: Path, doc: ExtractedDoc) -> None:
    from pypdf import PdfReader

    reader = PdfReader(str(path))
    if reader.is_encrypted:
        try:
            reader.decrypt("")
        except Exception:
            doc.error = "PDF is password protected"
            return

    info = reader.metadata or {}
    doc.meta = {
        "author": str(info.get("/Author", "") or ""),
        "creator": str(info.get("/Creator", "") or ""),
        "producer": str(info.get("/Producer", "") or ""),
        "created": str(info.get("/CreationDate", "") or ""),
        "modified": str(info.get("/ModDate", "") or ""),
    }
    doc.page_count = len(reader.pages)

    parts: list[str] = []
    for page in reader.pages:
        try:
            parts.append(page.extract_text() or "")
        except Exception:
            continue
    doc.text = _clean("\n".join(parts))

    # Scanned or image-only PDF: no usable text layer. Claude can still read the
    # file directly, so flag it for the vision path instead of rejecting here.
    if doc.char_count < 100:
        doc.needs_vision = True


def _extract_docx(path: Path, doc: ExtractedDoc) -> None:
    import docx

    d = docx.Document(str(path))
    parts = [p.text for p in d.paragraphs]
    for table in d.tables:
        for row in table.rows:
            parts.append(" | ".join(cell.text.strip() for cell in row.cells))
    doc.text = _clean("\n".join(parts))

    props = d.core_properties
    doc.meta = {
        "author": props.author or "",
        "last_modified_by": props.last_modified_by or "",
        "created": str(props.created or ""),
        "modified": str(props.modified or ""),
        "revision": str(props.revision or ""),
    }


def _extract_plain(path: Path, doc: ExtractedDoc) -> None:
    raw = path.read_text(encoding="utf-8", errors="replace")
    if path.suffix.lower() == ".rtf":
        raw = re.sub(r"\[a-z]+-?\d* ?", " ", raw)
        raw = raw.replace("{", " ").replace("}", " ")
    doc.text = _clean(raw)


def extract(path: str | Path) -> ExtractedDoc:
    """Extract text and metadata from one file. Never raises."""
    path = Path(path)
    doc = ExtractedDoc(path=path)

    if not path.exists():
        doc.error = "File not found"
        return doc

    suffix = path.suffix.lower()
    if suffix not in SUPPORTED_EXTENSIONS:
        doc.error = f"Unsupported file type '{suffix}'"
        return doc

    try:
        if suffix == ".pdf":
            _extract_pdf(path, doc)
        elif suffix == ".docx":
            _extract_docx(path, doc)
        elif suffix == ".doc":
            doc.error = "Legacy .doc is not supported - please convert to .docx or PDF"
        else:
            _extract_plain(path, doc)
    except Exception as exc:  # noqa: BLE001 - surface any parse failure as a verdict
        doc.error = f"{type(exc).__name__}: {exc}"

    return doc
