"""Pydantic models describing what Claude must return for every document."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from .config import ROLE_LABELS

RoleLabel = Literal[tuple(ROLE_LABELS)]  # type: ignore[valid-type]

DocumentType = Literal[
    "cv_resume",
    "cover_letter",
    "certificate_or_transcript",
    "academic_paper",
    "job_description",
    "portfolio_or_project_doc",
    "invoice_or_form",
    "other_document",
]

Seniority = Literal[
    "Student",
    "Intern",
    "Fresh Graduate",
    "Junior",
    "Mid-Level",
    "Senior",
    "Lead / Manager",
    "Unknown",
]

RejectReason = Literal[
    "none",
    "not_a_cv",
    "ai_generated",
    "unreadable",
    "insufficient_content",
]


class Verdict(BaseModel):
    """The full screening verdict for one document."""

    # --- What is this document? ---
    document_type: DocumentType = Field(
        description="What kind of document this actually is."
    )
    is_cv: bool = Field(
        description="True only if this is a genuine CV/resume for a job applicant."
    )

    # --- Who is the candidate? ---
    candidate_name: str = Field(description="Full name, or '' if not found.")
    email: str = Field(description="Primary email, or '' if not found.")
    phone: str = Field(description="Primary phone number, or '' if not found.")

    # --- What do they do? ---
    role_family: RoleLabel = Field(
        description=(
            "The single role family this candidate is applying for. Must be one of "
            "the allowed labels. Use 'Other' for a real job role that is genuinely "
            "not in the list, and 'Undetermined' when the document is not a CV or "
            "the role truly cannot be inferred."
        )
    )
    custom_role_title: str = Field(
        description=(
            "Only when role_family is 'Other': a short title for the real role "
            "(e.g. 'Pharmacist'). Otherwise ''."
        )
    )
    specialization: str = Field(
        description=(
            "The narrower specialization inside the role family, e.g. 'NLP & LLMs', "
            "'React / Next.js', 'Structural design'. '' if unclear."
        )
    )
    major: str = Field(
        description="Academic major or field of study, e.g. 'Data Science and AI'. '' if absent."
    )
    seniority: Seniority
    years_experience: float = Field(
        description="Best estimate of total professional years, 0 for students."
    )
    top_skills: list[str] = Field(description="Up to 12 concrete skills/tools.")
    role_confidence: int = Field(
        ge=0, le=100, description="Confidence in role_family, 0-100."
    )

    # --- Is it authentic? ---
    ai_generated_score: int = Field(
        ge=0,
        le=100,
        description=(
            "0 = clearly written by a human, 100 = clearly generated by an LLM. "
            "Judge the writing, not the layout."
        ),
    )
    ai_signals: list[str] = Field(
        description="Concrete evidence pointing to LLM generation. Quote the CV."
    )
    human_signals: list[str] = Field(
        description="Concrete evidence pointing to a genuine human-written CV."
    )

    # --- Is it a usable, professional CV? ---
    format_score: int = Field(
        ge=0,
        le=100,
        description=(
            "How closely the document matches the expected professional CV structure "
            "described in the reference standard. 0-100."
        ),
    )
    format_notes: str = Field(description="One or two sentences on structure/formatting.")
    missing_sections: list[str] = Field(
        description=(
            "Expected CV sections that are absent or effectively empty, from: "
            "contact, summary, education, experience, projects, skills. Report what "
            "is genuinely missing - not sections that are merely named differently, "
            "ordered differently, or merged into another one."
        )
    )
    quality_score: int = Field(
        ge=0, le=100, description="Overall CV quality: substance, clarity, evidence."
    )

    # --- Recommendation ---
    suggested_reject_reason: RejectReason = Field(
        description="'none' if the CV should be accepted."
    )
    reasoning: str = Field(
        description="2-4 sentences explaining the verdict, in English."
    )
