"""Pydantic models describing what Claude must return for every document."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from .config import ROLE_LABELS
from .job_profile import Importance

RoleLabel = Literal[tuple(ROLE_LABELS)]  # type: ignore[valid-type]

DocumentType = Literal[
    "cv_resume",
    "cover_letter",
    "certificate_or_transcript",
    "academic_paper",
    "job_description",
    "portfolio_or_project_doc",
    "invoice_or_form",
    "other_document",
]

Seniority = Literal[
    "Student",
    "Intern",
    "Fresh Graduate",
    "Junior",
    "Mid-Level",
    "Senior",
    "Lead / Manager",
    "Unknown",
]

RejectReason = Literal[
    "none",
    "not_a_cv",
    "ai_generated",
    "unreadable",
    "insufficient_content",
    "poor_structure",
    "unprofessional",
    "low_quality",
]


class Verdict(BaseModel):
    """The full screening verdict for one document."""

    # --- What is this document? ---
    document_type: DocumentType = Field(
        description="What kind of document this actually is."
    )
    is_cv: bool = Field(
        description="True only if this is a genuine CV/resume for a job applicant."
    )

    # --- Who is the candidate? ---
    candidate_name: str = Field(description="Full name, or '' if not found.")
    email: str = Field(description="Primary email, or '' if not found.")
    phone: str = Field(description="Primary phone number, or '' if not found.")

    # --- What do they do? ---
    role_family: RoleLabel = Field(
        description=(
            "The single role family this candidate is applying for. Must be one of "
            "the allowed labels. Use 'Other' for a real job role that is genuinely "
            "not in the list, and 'Undetermined' when the document is not a CV or "
            "the role truly cannot be inferred."
        )
    )
    custom_role_title: str = Field(
        description=(
            "Only when role_family is 'Other': a short title for the real role "
            "(e.g. 'Pharmacist'). Otherwise ''."
        )
    )
    specialization: str = Field(
        description=(
            "The narrower specialization inside the role family, e.g. 'NLP & LLMs', "
            "'React / Next.js', 'Structural design'. '' if unclear."
        )
    )
    major: str = Field(
        description="Academic major or field of study, e.g. 'Data Science and AI'. '' if absent."
    )
    seniority: Seniority
    years_experience: float = Field(
        description="Best estimate of total professional years, 0 for students."
    )
    top_skills: list[str] = Field(description="Up to 12 concrete skills/tools.")
    role_confidence: int = Field(
        ge=0, le=100, description="Confidence in role_family, 0-100."
    )

    # --- Is it authentic? ---
    ai_generated_score: int = Field(
        ge=0,
        le=100,
        description=(
            "0 = clearly written by a human, 100 = clearly generated by an LLM. "
            "Judge the writing, not the layout."
        ),
    )
    ai_signals: list[str] = Field(
        description="Concrete evidence pointing to LLM generation. Quote the CV."
    )
    human_signals: list[str] = Field(
        description="Concrete evidence pointing to a genuine human-written CV."
    )

    # --- Is it a usable, professional CV? ---
    format_score: int = Field(
        ge=0,
        le=100,
        description=(
            "How closely the document matches the expected professional CV structure "
            "described in the reference standard. 0-100."
        ),
    )
    format_notes: str = Field(description="One or two sentences on structure/formatting.")
    structure_issues: list[str] = Field(
        description=(
            "Concrete structural problems that make this CV hard to read or to "
            "parse: no section headings, one wall of text, employment dates absent, "
            "content trapped in images, contact details missing. Quote or point at "
            "what you mean. Empty list if the structure is fine."
        )
    )
    professionalism_score: int = Field(
        ge=0,
        le=100,
        description=(
            "How professionally the CV presents its author. 100 = entirely "
            "appropriate for a job application. Judge register and appropriateness "
            "ONLY - never the person's background, country, language ability, or "
            "how expensive their template looks."
        ),
    )
    professionalism_issues: list[str] = Field(
        description=(
            "Concrete lapses in professional presentation, each with the evidence: "
            "a joke or inappropriate email address, slang or chat-speak, emojis, "
            "offensive or oversharing content, pervasive typos, an unfinished "
            "sentence left in. Empty list if there are none."
        )
    )
    missing_sections: list[str] = Field(
        description=(
            "Expected CV sections that are absent or effectively empty, from: "
            "contact, summary, education, experience, projects, skills. Report what "
            "is genuinely missing - not sections that are merely named differently, "
            "ordered differently, or merged into another one."
        )
    )
    quality_score: int = Field(
        ge=0, le=100, description="Overall CV quality: substance, clarity, evidence."
    )

    # --- Recommendation ---
    suggested_reject_reason: RejectReason = Field(
        description="'none' if the CV should be accepted."
    )
    reasoning: str = Field(
        description="2-4 sentences explaining the verdict, in English."
    )


# --------------------------------------------------------------------------
# Screening against a job description
# --------------------------------------------------------------------------
MatchStatus = Literal["met", "partial", "not_met", "unclear"]

Overall = Literal["strong_match", "partial_match", "not_a_match"]


class RequirementMatch(BaseModel):
    """One requirement, checked against one CV, with the evidence attached."""

    requirement: str = Field(description="The requirement text, copied verbatim.")
    importance: Importance
    status: MatchStatus = Field(
        description=(
            "'met' - the CV clearly shows it. 'partial' - close but short (asked for "
            "5 years, has 3; asked for advanced, has intermediate). 'not_met' - "
            "nothing in the CV supports it. 'unclear' - the CV hints at it but is "
            "too vague to call, which is a prompt for a human to look, not a fail."
        )
    )
    evidence: str = Field(
        description=(
            "The exact words from the CV that justify this, quoted. Empty string "
            "when the status is not_met. Never paraphrase into something the CV "
            "does not say - a rejected candidate may ask to see this."
        )
    )


class MatchVerdict(BaseModel):
    """What HR sees: does this person meet what the job asked for?"""

    # --- What is this document, and whose? ---
    document_type: DocumentType
    is_cv: bool
    candidate_name: str = Field(description="Full name, or '' if not found.")
    email: str = Field(description="Primary email, or '' if not found.")
    phone: str = Field(description="Primary phone, or '' if not found.")
    current_title: str = Field(description="Their most recent job title, or ''.")
    years_experience: float = Field(description="Total professional years, 0 for students.")

    # --- The match ---
    requirement_matches: list[RequirementMatch] = Field(
        description=(
            "One entry for EVERY requirement in the job profile, in the same order. "
            "Never omit one, never invent one."
        )
    )
    overall: Overall = Field(
        description=(
            "'strong_match' - every must-have met. 'partial_match' - most must-haves "
            "met, one or two short or unclear. 'not_a_match' - several must-haves "
            "genuinely absent. Judge on must-haves; nice-to-haves only separate "
            "candidates who already clear the bar."
        )
    )
    strengths: list[str] = Field(
        description="Up to 4 things this candidate brings, beyond just meeting the list."
    )
    gaps: list[str] = Field(
        description="Up to 4 concrete gaps against this job, in plain language."
    )
    summary: str = Field(
        description=(
            "One or two sentences a recruiter can read and act on, and could show "
            "the candidate. No scores, no jargon."
        )
    )

    # --- Authenticity, kept as a flag rather than a verdict ---
    ai_generated_score: int = Field(
        ge=0, le=100, description="Probability the CV's substance was LLM-generated."
    )
    ai_signals: list[str] = Field(description="Concrete evidence, quoted from the CV.")

    @property
    def must_have_matches(self) -> list[RequirementMatch]:
        return [m for m in self.requirement_matches if m.importance == "must_have"]

    @property
    def must_haves_met(self) -> int:
        return sum(1 for m in self.must_have_matches if m.status == "met")

    @property
    def must_haves_total(self) -> int:
        return len(self.must_have_matches)
